In [1]:
import pandas as pd

# resultados de todos los modelos

In [2]:
df = pd.read_csv('models/results/hf_evaluation_results.csv')
df

,model_name,num_params,languages,map_es_es,mrr,ndcg,p@5,p@10,p@100
0,shtilev/medical_embedded_v4,278043648,multilingual,0.426456,0.545946,0.722666,0.647568,0.626486,0.230919
1,sentence-transformers/paraphrase-multilingual-...,278043648,multilingual,0.416908,0.551892,0.719501,0.640000,0.602162,0.226000
2,Alibaba-NLP/gte-multilingual-base,305368320,multilingual,0.415536,0.541441,0.722481,0.627027,0.614595,0.226054
3,shtilev/medical_embedded_v5,278043648,multilingual,0.411697,0.544144,0.714826,0.636757,0.610270,0.224811
4,upskyy/e5-large-korean,559890432,multilingual,0.405835,0.546126,0.719760,0.622703,0.614054,0.225459
5,upskyy/gte-base-korean,305368320,multilingual,0.401787,0.563063,0.717950,0.627027,0.601622,0.221514
6,upskyy/e5-base-korean,278043648,multilingual,0.395251,0.540991,0.713011,0.634595,0.610270,0.219676
7,ibm-granite/granite-embedding-278m-multilingual,278043648,multilingual,0.392120,0.551223,0.712323,0.616216,0.598919,0.216216
8,OneFly7/biencoder_ep10_bs64_trans1,278043648,multilingual,0.390109,0.557387,0.706117,0.615135,0.573514,0.217351
9,shtilev/medical_embedded_v3,278043648,multilingual,0.387537,0.552613,0.703050,0.619459,0.584324,0.218324
10,OneFly7/bi_bs32_lr2e5_cosine_restart_period2_best,278043648,multilingual,0.384700,0.549189,0.700359,0.616216,0.589730,0.213351
11,sentence-transformers/paraphrase-multilingual-...,117653760,multilingual,0.376560,0.541937,0.697857,0.607568,0.572973,0.211784
12,tomaarsen/distiluse-base-multilingual-cased-v2,134734080,multilingual,0.374899,0.547131,0.698524,0.625946,0.585946,0.201135
13,OneFly7/biencoder_ep2_bs32_trans3,278043648,multilingual,0.369983,0.548086,0.692253,0.624865,0.576216,0.205946
14,upskyy/bge-m3-korean,567754752,multilingual,0.369236,0.544324,0.696324,0.608649,0.587027,0.202865
15,lang-uk/ukr-paraphrase-multilingual-mpnet-base,278043648,multilingual,0.369205,0.538981,0.690901,0.594595,0.568108,0.208811
16,Griffin88/sentence-embedding-LaBSE,471517440,multilingual,0.366081,0.548430,0.695912,0.600000,0.562703,0.209730
17,OneFly7/biencoder_ep10_bs32_lr2e5_cosine_annea...,278043648,multilingual,0.364243,0.552252,0.689232,0.609730,0.563784,0.208595
18,OneFly7/biencoder_ep10_bs64_trans3,278043648,multilingual,0.361339,0.539745,0.687390,0.598919,0.562703,0.202919
19,hiiamsid/sentence_similarity_spanish_es,109850880,monolingual,0.360081,0.538239,0.696669,0.616216,0.571351,0.209568
20,OneFly7/biencoder_ep10_bs64_all,278043648,multilingual,0.359179,0.541763,0.686018,0.595676,0.563243,0.202486
21,DmitryML/distiluse-base-multilingual-cased-v1,135127808,multilingual,0.354914,0.546372,0.684185,0.588108,0.563784,0.200216
22,upskyy/e5-small-korean,117653760,multilingual,0.354480,0.545495,0.689597,0.608649,0.581081,0.198486
23,emersoftware/tulio-chilean-spanish-bert-finetu...,109850880,monolingual,0.347058,0.542122,0.684869,0.600000,0.558378,0.202432
24,OneFly7/biencoder_ep10_bs32_lr2e5_cosine_annea...,278043648,multilingual,0.345871,0.538018,0.678539,0.591351,0.553514,0.195243
25,mrm8488/distiluse-base-multilingual-cased-v2-f...,134734080,multilingual,0.342060,0.548739,0.678785,0.589189,0.547568,0.193459
26,symanto/sn-xlm-roberta-base-snli-mnli-anli-xnli,278043648,multilingual,0.336776,0.528866,0.676368,0.587027,0.534595,0.192649
27,h4g3n/multilingual-MiniLM-L12-de-en-es-fr-it-n...,103458048,multilingual,0.332636,0.540335,0.667232,0.590270,0.554054,0.189189
28,narraticlabs/MiniLM-L6-european-union,107006976,multilingual,0.323116,0.523311,0.659535,0.556757,0.528649,0.183838
29,Maite89/Roberta_finetuning_semantic_similarity...,355356672,monolingual,0.318717,0.519766,0.669148,0.572973,0.536216,0.194054
30,OneFly7/biencoder_ep10_bs32_trans3,278043648,multilingual,0.310323,0.531847,0.655888,0.557838,0.530270,0.180378
31,somosnlp-hackathon-2022/paraphrase-spanish-dis...,124645632,monolingual,0.306394,0.501105,0.643751,0.520000,0.489730,0.193946
32,chukbert/paraphrase-multilingual-MiniLM-L12-v2...,117653760,multilingual,0.302337,0.530904,0.648583,0.547027,0.520000,0.175189
33,LinerAI/Qwen3-Embedding-0.6B-academic,595776512,multilingual,0.299076,0.543063,0.655802,0.562162,0.507027,0.181351
34,jaimevera1107/all-MiniLM-L6-v2-similarity-es,22713216,monolingual,0.297729,0.525109,0.636365,0.589189,0.551892,0.164486
35,facebook/drama-large,399803392,multilingual,0.290471,0.543217,0.648744,0.567568,0.488108,0.165459
36,facebook/drama-1b,1235814400,multilingual,0.286316,0.550174,0.645776,0.568649,0.494595,0.162811
37,clips/mfaq,278045952,multilingual,0.266298,0.534996,0.633210,0.525405,0.478919,0.166811
38,OneFly7/crossencoder_ep10_bs8_trans1,278043648,multilingual,0.260387,0.537583,0.618162,0.541622,0.487027,0.165459
39,facebook/drama-base,211766016,multilingual,0.258691,0.538677,0.625515,0.555676,0.465946,0.152054
40,0xnu/pmmlv2-fine-tuned-igbo,117653760,multilingual,0.110013,0.486003,0.490691,0.368649,0.284324,0.076865
41,0xnu/pmmlv2-fine-tuned-hausa,117653760,multilingual,0.107842,0.469792,0.487138,0.371892,0.291892,0.075730
42,0xnu/pmmlv2-fine-tuned-yoruba,117653760,multilingual,0.105249,0.485193,0.485622,0.364324,0.277838,0.072865
43,0xnu/pmmlv2-fine-tuned-flemish,117653760,multilingual,0.099794,0.471253,0.481064,0.360000,0.264865,0.070757
44,j0h4nnes/decoy-ify_llama3.1_8B_v2,117653760,multilingual,0.094253,0.427073,0.468344,0.339459,0.278919,0.072973

In [3]:
df.query('languages == "monolingual"')

,model_name,num_params,languages,map_es_es,mrr,ndcg,p@5,p@10,p@100
19,hiiamsid/sentence_similarity_spanish_es,109850880,monolingual,0.360081,0.538239,0.696669,0.616216,0.571351,0.209568
23,emersoftware/tulio-chilean-spanish-bert-finetu...,109850880,monolingual,0.347058,0.542122,0.684869,0.600000,0.558378,0.202432
29,Maite89/Roberta_finetuning_semantic_similarity...,355356672,monolingual,0.318717,0.519766,0.669148,0.572973,0.536216,0.194054
31,somosnlp-hackathon-2022/paraphrase-spanish-dis...,124645632,monolingual,0.306394,0.501105,0.643751,0.520000,0.489730,0.193946
34,jaimevera1107/all-MiniLM-L6-v2-similarity-es,22713216,monolingual,0.297729,0.525109,0.636365,0.589189,0.551892,0.164486

# Ranking MTEB

In [17]:
mteb = pd.read_csv('models/mteb-leaderboard-openmodels-retrieval.csv', index_col=0)
mteb

,Model_Name,Memory Usage (MB),Number of Parameters,Rank (Borda),Retrieval,Model_Link,Short_Name
0,nvidia/llama-embed-nemotron-8b,28629.0,7.000000e+09,1,68.69,https://huggingface.co/nvidia/llama-embed-nemo...,llama-embed-nemotron-8b
1,tencent/KaLM-Embedding-Gemma3-12B-2511,44884.0,1.100000e+10,2,75.66,https://kalm-embedding.github.io/,KaLM-Embedding-Gemma3-12B-2511
2,Qwen/Qwen3-Embedding-8B,14433.0,7.000000e+09,3,70.88,https://huggingface.co/Qwen/Qwen3-Embedding-8B,Qwen3-Embedding-8B
3,Qwen/Qwen3-Embedding-4B,7671.0,4.000000e+09,4,69.60,https://huggingface.co/Qwen/Qwen3-Embedding-4B,Qwen3-Embedding-4B
4,infly/inf-retriever-v1,13483.0,7.000000e+09,5,66.48,https://huggingface.co/infly/inf-retriever-v1,inf-retriever-v1
...,...,...,...,...,...,...,...
143,cointegrated/rubert-tiny2,45.0,1.100000e+07,144,12.09,https://huggingface.co/cointegrated/rubert-tiny,rubert-tiny
144,DeepPavlov/rubert-base-cased,4883.0,1.000000e+09,145,7.97,https://huggingface.co/DeepPavlov/rubert-base-...,rubert-base-cased
145,ai-forever/sbert_large_nlu_ru,1629.0,4.270000e+08,146,7.80,https://huggingface.co/ai-forever/sbert_large_...,sbert_large_nlu_ru
146,ai-forever/sbert_large_mt_nlu_ru,1629.0,4.270000e+08,147,8.47,https://huggingface.co/ai-forever/sbert_large_...,sbert_large_mt_nlu_ru
147,binhquoc/deberta-v1-base,473.0,1.240000e+08,148,6.63,https://huggingface.co/deepvk/deberta-v1-base,deberta-v1-base

In [20]:
mteb.head(99).sort_values('Memory Usage (MB)', ascending=False)[['Model_Name', 'Memory Usage (MB)']].head(20)

                                           Model_Name  Memory Usage (MB)
15                                 GritLM/GritLM-8x7B            89079.0
1              tencent/KaLM-Embedding-Gemma3-12B-2511            44884.0
6                   Alibaba-NLP/gte-Qwen2-7B-instruct            29040.0
0                      nvidia/llama-embed-nemotron-8b            28629.0
50  McGill-NLP/LLM2Vec-Mistral-7B-Instruct-v2-mntp...            27126.0
18                                 nvidia/NV-Embed-v1            14975.0
10                                 nvidia/NV-Embed-v2            14975.0
2                             Qwen/Qwen3-Embedding-8B            14433.0
13                         parasail-ai/GritLM-7B-vllm            13813.0
7                 Linq-AI-Research/Linq-Embed-Mistral            13563.0
14                   Salesforce/SFR-Embedding-Mistral            13563.0
19                    intfloat/e5-mistral-7b-instruct            13563.0
16                       Salesforce/SFR-Embedding-2_R            13563.0
4                              infly/inf-retriever-v1            13483.0
3                             Qwen/Qwen3-Embedding-4B             7671.0
5                           jinaai/jina-embeddings-v4             7500.0
8                 Alibaba-NLP/gte-Qwen2-1.5B-instruct             6776.0
22                       NovaSearch/stella_en_1.5B_v5             5887.0
17            NovaSearch/jasper_en_vision_language_v1             3802.0
12                        infly/inf-retriever-v1-1.5b             2944.0

In [31]:
mteb_list = mteb.head(99).query('`Memory Usage (MB)` < 20000').sort_values('Memory Usage (MB)', ascending=False)[['Model_Name']].values.tolist()
mteb_list = [item for sublist in mteb_list for item in sublist]

mteb_list

['nvidia/NV-Embed-v2',
 'nvidia/NV-Embed-v1',
 'Qwen/Qwen3-Embedding-8B',
 'parasail-ai/GritLM-7B-vllm',
 'Linq-AI-Research/Linq-Embed-Mistral',
 'Salesforce/SFR-Embedding-Mistral',
 'Salesforce/SFR-Embedding-2_R',
 'intfloat/e5-mistral-7b-instruct',
 'infly/inf-retriever-v1',
 'Qwen/Qwen3-Embedding-4B',
 'jinaai/jina-embeddings-v4',
 'Alibaba-NLP/gte-Qwen2-1.5B-instruct',
 'NovaSearch/stella_en_1.5B_v5',
 'NovaSearch/jasper_en_vision_language_v1',
 'infly/inf-retriever-v1-1.5b',
 'manu/sentence_croissant_alpha_v0.2',
 'manu/sentence_croissant_alpha_v0.3',
 'manu/sentence_croissant_alpha_v0.4',
 'BAAI/bge-m3',
 'Snowflake/snowflake-arctic-embed-l-v2.0',
 'gandolfi/bge-m3-custom-fr-Q4_K_M-GGUF',
 'OrdalieTech/Solon-embeddings-large-0.1',
 'intfloat/multilingual-e5-large',
 'sdadas/mmlw-e5-large',
 'Lajavaness/bilingual-embedding-large',
 'HIT-TMG/KaLM-embedding-multilingual-mini-instruct-v1',
 'HIT-TMG/KaLM-embedding-multilingual-mini-v1',
 'Omartificial-Intelligence-Space/Arabic-labse-Matryoshka',
 'NovaSearch/stella_en_400M_v5',
 'sdadas/mmlw-roberta-large',
 'deepvk/USER-bge-m3',
 'intfloat/multilingual-e5-large',
 'avsolatorio/GIST-large-Embedding-v0',
 'intfloat/e5-large-v2',
 'WhereIsAI/UAE-Large-V1',
 'Snowflake/snowflake-arctic-embed-l-v2.0',
 'BAAI/bge-large-en-v1.5',
 'Snowflake/snowflake-arctic-embed-m-v2.0',
 'google/embeddinggemma-300m',
 'Qwen/Qwen3-Embedding-0.6B',
 'jinaai/jina-embeddings-v3',
 'intfloat/multilingual-e5-large-instruct',
 'Lajavaness/bilingual-embedding-base',
 'Omartificial-Intelligence-Space/Arabic-all-nli-triplet-Matryoshka',
 'AIDA-UPM/mstsb-paraphrase-multilingual-mpnet-base-v2',
 'chienpham/sts-multilingual-mpnet-base-v2',
 'intfloat/multilingual-e5-base',
 'sdadas/mmlw-e5-base',
 'mixedbread-ai/mxbai-embed-large-v1',
 'thenlper/gte-large',
 'Alibaba-NLP/gte-multilingual-base',
 'ibm-granite/granite-embedding-278m-multilingual',
 'Snowflake/snowflake-arctic-embed-m-long',
 'nomic-ai/nomic-embed-text-v1.5',
 'nomic-ai/nomic-embed-text-v1.5',
 'minishlab/potion-multilingual-128M',
 'intfloat/multilingual-e5-small',
 'Lajavaness/bilingual-embedding-small',
 'sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2',
 'Omartificial-Intelligence-Space/Arabic-MiniLM-L12-v2-all-nli-triplet',
 'jinaai/jina-embedding-b-en-v1',
 'intfloat/multilingual-e5-base',
 'sentence-transformers/all-mpnet-base-v2',
 'intfloat/e5-base-v2',
 'avsolatorio/GIST-Embedding-v0',
 'Snowflake/snowflake-arctic-embed-m-v1.5',
 'Snowflake/snowflake-arctic-embed-m-v1.5',
 'sentence-transformers/static-similarity-mrl-multilingual-v1',
 nan,
 'BAAI/bge-base-en-v1.5',
 'ibm-granite/granite-embedding-125m-english',
 'thenlper/gte-base',
 'bartowski/granite-embedding-107m-multilingual-GGUF',
 'jinaai/jina-embedding-s-en-v1',
 'BAAI/bge-small-en-v1.5',
 'avsolatorio/GIST-small-Embedding-v0',
 'intfloat/e5-small-v2',
 'Snowflake/snowflake-arctic-embed-s',
 'avsolatorio/NoInstruct-small-Embedding-v0',
 'abhinand/MedEmbed-small-v0.1',
 'intfloat/multilingual-e5-small',
 'sentence-transformers/all-MiniLM-L12-v2',
 'sentence-transformers/all-MiniLM-L6-v2',
 'avsolatorio/GIST-all-MiniLM-L6-v2',
 'brahmairesearch/slx-v0.1',
 'Mihaiii/Ivysaur',
 'Snowflake/snowflake-arctic-embed-l-v2.0',
 'thenlper/gte-small',
 'ibm-granite/granite-embedding-30m-english']

In [32]:
# exportar lista a txt
with open('mteb_models.txt', 'w') as f:
    for item in mteb_list:
        f.write("%s\n" % item)

# Spanish models

In [53]:
from huggingface_hub import list_models

# Lista de autores
autores = ["PlanTL-GOB-ES", "dccuchile"]
librerias = ["transformers", "sentence-transformers"]

# Recopilar modelos de todos los autores
todos_los_modelos = []

for libreria in librerias:
    for autor in autores:
        modelos = list(list_models(
            author=autor,
            library=libreria,
        ))
        todos_los_modelos.extend(modelos)

# Ordenar por ID
todos_los_modelos = sorted(todos_los_modelos, key=lambda x: x.id)

# Mostrar los modelos
print(f"Total de modelos encontrados: {len(todos_los_modelos)}\n")
for model in todos_los_modelos:
    print(model.id)

/home/david/Documents/Master/TFM/.venv/lib/python3.12/site-packages/huggingface_hub/utils/_deprecation.py:100: FutureWarning: Deprecated argument(s) used in 'list_models': library. Will not be supported from version '1.0'.

Use `filter` instead.
  warnings.warn(message, FutureWarning)

Total de modelos encontrados: 210

PlanTL-GOB-ES/Controversy-Prediction
PlanTL-GOB-ES/RoBERTalex
PlanTL-GOB-ES/bsc-bio-ehr-es
PlanTL-GOB-ES/bsc-bio-ehr-es-cantemist
PlanTL-GOB-ES/bsc-bio-ehr-es-pharmaconer
PlanTL-GOB-ES/bsc-bio-es
PlanTL-GOB-ES/longformer-base-4096-biomedical-clinical-es
PlanTL-GOB-ES/roberta-base-biomedical-clinical-es
PlanTL-GOB-ES/roberta-base-biomedical-es
PlanTL-GOB-ES/roberta-base-ca
PlanTL-GOB-ES/roberta-base-es-wikicat-es
dccuchile/albert-base-10-spanish
dccuchile/albert-base-10-spanish-distilled-mldoc
dccuchile/albert-base-10-spanish-distilled-ner
dccuchile/albert-base-10-spanish-distilled-pawsx
dccuchile/albert-base-10-spanish-distilled-pos
dccuchile/albert-base-10-spanish-distilled-qa-mlqa
dccuchile/albert-base-10-spanish-distilled-qa-sqac
dccuchile/albert-base-10-spanish-distilled-qa-tar
dccuchile/albert-base-10-spanish-distilled-xnli
dccuchile/albert-base-10-spanish-finetuned-mldoc
dccuchile/albert-base-10-spanish-finetuned-ner
dccuchile/albert-base-10-spanish-finetuned-pawsx
dccuchile/albert-base-10-spanish-finetuned-pos
dccuchile/albert-base-10-spanish-finetuned-qa-mlqa
dccuchile/albert-base-10-spanish-finetuned-qa-sqac
dccuchile/albert-base-10-spanish-finetuned-qa-tar
dccuchile/albert-base-10-spanish-finetuned-xnli
dccuchile/albert-base-2-spanish
dccuchile/albert-base-2-spanish-distilled-mldoc
dccuchile/albert-base-2-spanish-distilled-ner
dccuchile/albert-base-2-spanish-distilled-pawsx
dccuchile/albert-base-2-spanish-distilled-pos
dccuchile/albert-base-2-spanish-distilled-qa-mlqa
dccuchile/albert-base-2-spanish-distilled-qa-sqac
dccuchile/albert-base-2-spanish-distilled-qa-tar
dccuchile/albert-base-2-spanish-distilled-xnli
dccuchile/albert-base-2-spanish-finetuned-mldoc
dccuchile/albert-base-2-spanish-finetuned-ner
dccuchile/albert-base-2-spanish-finetuned-pawsx
dccuchile/albert-base-2-spanish-finetuned-pos
dccuchile/albert-base-2-spanish-finetuned-qa-mlqa
dccuchile/albert-base-2-spanish-finetuned-qa-sqac
dccuchile/albert-base-2-spanish-finetuned-qa-tar
dccuchile/albert-base-2-spanish-finetuned-xnli
dccuchile/albert-base-4-spanish
dccuchile/albert-base-4-spanish-distilled-mldoc
dccuchile/albert-base-4-spanish-distilled-ner
dccuchile/albert-base-4-spanish-distilled-pawsx
dccuchile/albert-base-4-spanish-distilled-pos
dccuchile/albert-base-4-spanish-distilled-qa-mlqa
dccuchile/albert-base-4-spanish-distilled-qa-sqac
dccuchile/albert-base-4-spanish-distilled-qa-tar
dccuchile/albert-base-4-spanish-distilled-xnli
dccuchile/albert-base-4-spanish-finetuned-mldoc
dccuchile/albert-base-4-spanish-finetuned-ner
dccuchile/albert-base-4-spanish-finetuned-pawsx
dccuchile/albert-base-4-spanish-finetuned-pos
dccuchile/albert-base-4-spanish-finetuned-qa-mlqa
dccuchile/albert-base-4-spanish-finetuned-qa-sqac
dccuchile/albert-base-4-spanish-finetuned-qa-tar
dccuchile/albert-base-4-spanish-finetuned-xnli
dccuchile/albert-base-6-spanish
dccuchile/albert-base-6-spanish-distilled-mldoc
dccuchile/albert-base-6-spanish-distilled-ner
dccuchile/albert-base-6-spanish-distilled-pawsx
dccuchile/albert-base-6-spanish-distilled-pos
dccuchile/albert-base-6-spanish-distilled-qa-mlqa
dccuchile/albert-base-6-spanish-distilled-qa-sqac
dccuchile/albert-base-6-spanish-distilled-qa-tar
dccuchile/albert-base-6-spanish-distilled-xnli
dccuchile/albert-base-6-spanish-finetuned-mldoc
dccuchile/albert-base-6-spanish-finetuned-ner
dccuchile/albert-base-6-spanish-finetuned-pawsx
dccuchile/albert-base-6-spanish-finetuned-pos
dccuchile/albert-base-6-spanish-finetuned-qa-mlqa
dccuchile/albert-base-6-spanish-finetuned-qa-sqac
dccuchile/albert-base-6-spanish-finetuned-qa-tar
dccuchile/albert-base-6-spanish-finetuned-xnli
dccuchile/albert-base-8-spanish
dccuchile/albert-base-8-spanish-distilled-mldoc
dccuchile/albert-base-8-spanish-distilled-ner
dccuchile/albert-base-8-spanish-distilled-pawsx
dccuchile/albert-base-8-spanish-distilled-pos
dccuchile/albert-base-8-spanish-distilled-qa-mlqa
dccuchile/albert-base-8-spanish-distilled-qa-sqac
dccuchile/albert-base-8-spanish-distilled-qa-tar
dccuchile/albert-base-8-spanish-distilled-xnli
dccuchile/albert-base-8-spanish-finetuned-mldoc
dccuchile/albert-base-8-spanish-finetuned-ner
dccuchile/albert-base-8-spanish-finetuned-pawsx
dccuchile/albert-base-8-spanish-finetuned-pos
dccuchile/albert-base-8-spanish-finetuned-qa-mlqa
dccuchile/albert-base-8-spanish-finetuned-qa-sqac
dccuchile/albert-base-8-spanish-finetuned-qa-tar
dccuchile/albert-base-8-spanish-finetuned-xnli
dccuchile/albert-base-spanish
dccuchile/albert-base-spanish-distilled-mldoc
dccuchile/albert-base-spanish-distilled-ner
dccuchile/albert-base-spanish-distilled-pawsx
dccuchile/albert-base-spanish-distilled-pos
dccuchile/albert-base-spanish-distilled-qa-mlqa
dccuchile/albert-base-spanish-distilled-qa-sqac
dccuchile/albert-base-spanish-distilled-qa-tar
dccuchile/albert-base-spanish-distilled-xnli
dccuchile/albert-base-spanish-finetuned-mldoc
dccuchile/albert-base-spanish-finetuned-ner
dccuchile/albert-base-spanish-finetuned-pawsx
dccuchile/albert-base-spanish-finetuned-pos
dccuchile/albert-base-spanish-finetuned-qa-mlqa
dccuchile/albert-base-spanish-finetuned-qa-sqac
dccuchile/albert-base-spanish-finetuned-qa-tar
dccuchile/albert-base-spanish-finetuned-xnli
dccuchile/albert-large-spanish
dccuchile/albert-large-spanish-finetuned-mldoc
dccuchile/albert-large-spanish-finetuned-ner
dccuchile/albert-large-spanish-finetuned-pawsx
dccuchile/albert-large-spanish-finetuned-pos
dccuchile/albert-large-spanish-finetuned-qa-mlqa
dccuchile/albert-large-spanish-finetuned-qa-sqac
dccuchile/albert-large-spanish-finetuned-qa-tar
dccuchile/albert-large-spanish-finetuned-xnli
dccuchile/albert-tiny-spanish
dccuchile/albert-tiny-spanish-distilled-mldoc
dccuchile/albert-tiny-spanish-distilled-ner
dccuchile/albert-tiny-spanish-distilled-pawsx
dccuchile/albert-tiny-spanish-distilled-pos
dccuchile/albert-tiny-spanish-distilled-qa-mlqa
dccuchile/albert-tiny-spanish-distilled-qa-sqac
dccuchile/albert-tiny-spanish-distilled-qa-tar
dccuchile/albert-tiny-spanish-distilled-xnli
dccuchile/albert-tiny-spanish-finetuned-mldoc
dccuchile/albert-tiny-spanish-finetuned-ner
dccuchile/albert-tiny-spanish-finetuned-pawsx
dccuchile/albert-tiny-spanish-finetuned-pos
dccuchile/albert-tiny-spanish-finetuned-qa-mlqa
dccuchile/albert-tiny-spanish-finetuned-qa-sqac
dccuchile/albert-tiny-spanish-finetuned-qa-tar
dccuchile/albert-tiny-spanish-finetuned-xnli
dccuchile/albert-xlarge-spanish
dccuchile/albert-xlarge-spanish-finetuned-mldoc
dccuchile/albert-xlarge-spanish-finetuned-ner
dccuchile/albert-xlarge-spanish-finetuned-pawsx
dccuchile/albert-xlarge-spanish-finetuned-pos
dccuchile/albert-xlarge-spanish-finetuned-qa-mlqa
dccuchile/albert-xlarge-spanish-finetuned-qa-sqac
dccuchile/albert-xlarge-spanish-finetuned-qa-tar
dccuchile/albert-xlarge-spanish-finetuned-xnli
dccuchile/albert-xxlarge-spanish
dccuchile/albert-xxlarge-spanish-finetuned-mldoc
dccuchile/albert-xxlarge-spanish-finetuned-ner
dccuchile/albert-xxlarge-spanish-finetuned-pawsx
dccuchile/albert-xxlarge-spanish-finetuned-pos
dccuchile/albert-xxlarge-spanish-finetuned-qa-mlqa
dccuchile/albert-xxlarge-spanish-finetuned-qa-sqac
dccuchile/albert-xxlarge-spanish-finetuned-qa-tar
dccuchile/albert-xxlarge-spanish-finetuned-xnli
dccuchile/bert-base-spanish-wwm-cased
dccuchile/bert-base-spanish-wwm-cased-finetuned-mldoc
dccuchile/bert-base-spanish-wwm-cased-finetuned-ner
dccuchile/bert-base-spanish-wwm-cased-finetuned-pawsx
dccuchile/bert-base-spanish-wwm-cased-finetuned-pos
dccuchile/bert-base-spanish-wwm-cased-finetuned-qa-mlqa
dccuchile/bert-base-spanish-wwm-cased-finetuned-qa-sqac
dccuchile/bert-base-spanish-wwm-cased-finetuned-qa-tar
dccuchile/bert-base-spanish-wwm-cased-finetuned-xnli
dccuchile/bert-base-spanish-wwm-uncased
dccuchile/bert-base-spanish-wwm-uncased-finetuned-mldoc
dccuchile/bert-base-spanish-wwm-uncased-finetuned-ner
dccuchile/bert-base-spanish-wwm-uncased-finetuned-pawsx
dccuchile/bert-base-spanish-wwm-uncased-finetuned-pos
dccuchile/bert-base-spanish-wwm-uncased-finetuned-qa-mlqa
dccuchile/bert-base-spanish-wwm-uncased-finetuned-qa-sqac
dccuchile/bert-base-spanish-wwm-uncased-finetuned-qa-tar
dccuchile/bert-base-spanish-wwm-uncased-finetuned-xnli
dccuchile/bertin-roberta-base-spanish-finetuned-mldoc
dccuchile/bertin-roberta-base-spanish-finetuned-ner
dccuchile/bertin-roberta-base-spanish-finetuned-pawsx
dccuchile/bertin-roberta-base-spanish-finetuned-pos
dccuchile/bertin-roberta-base-spanish-finetuned-qa-mlqa
dccuchile/bertin-roberta-base-spanish-finetuned-qa-sqac
dccuchile/bertin-roberta-base-spanish-finetuned-qa-tar
dccuchile/bertin-roberta-base-spanish-finetuned-xnli
dccuchile/distilbert-base-spanish-uncased
dccuchile/distilbert-base-spanish-uncased-finetuned-mldoc
dccuchile/distilbert-base-spanish-uncased-finetuned-ner
dccuchile/distilbert-base-spanish-uncased-finetuned-pawsx
dccuchile/distilbert-base-spanish-uncased-finetuned-pos
dccuchile/distilbert-base-spanish-uncased-finetuned-qa-mlqa
dccuchile/distilbert-base-spanish-uncased-finetuned-qa-sqac
dccuchile/distilbert-base-spanish-uncased-finetuned-qa-tar
dccuchile/distilbert-base-spanish-uncased-finetuned-xnli
dccuchile/patana-chilean-spanish-bert
dccuchile/roberta-base-bne-finetuned-mldoc
dccuchile/roberta-base-bne-finetuned-ner
dccuchile/roberta-base-bne-finetuned-pawsx
dccuchile/roberta-base-bne-finetuned-pos
dccuchile/roberta-base-bne-finetuned-qa-mlqa
dccuchile/roberta-base-bne-finetuned-qa-sqac
dccuchile/roberta-base-bne-finetuned-qa-tar
dccuchile/roberta-base-bne-finetuned-xnli
dccuchile/roberta-large-bne-finetuned-mldoc
dccuchile/roberta-large-bne-finetuned-ner
dccuchile/roberta-large-bne-finetuned-pawsx
dccuchile/roberta-large-bne-finetuned-pos
dccuchile/roberta-large-bne-finetuned-qa-mlqa
dccuchile/roberta-large-bne-finetuned-qa-sqac
dccuchile/roberta-large-bne-finetuned-qa-tar
dccuchile/roberta-large-bne-finetuned-xnli
dccuchile/tulio-chilean-spanish-bert

In [55]:

model_list = [model.id for model in todos_los_modelos if 'finetuned' not in model.id]
model_list

['PlanTL-GOB-ES/Controversy-Prediction',
 'PlanTL-GOB-ES/RoBERTalex',
 'PlanTL-GOB-ES/bsc-bio-ehr-es',
 'PlanTL-GOB-ES/bsc-bio-ehr-es-cantemist',
 'PlanTL-GOB-ES/bsc-bio-ehr-es-pharmaconer',
 'PlanTL-GOB-ES/bsc-bio-es',
 'PlanTL-GOB-ES/longformer-base-4096-biomedical-clinical-es',
 'PlanTL-GOB-ES/roberta-base-biomedical-clinical-es',
 'PlanTL-GOB-ES/roberta-base-biomedical-es',
 'PlanTL-GOB-ES/roberta-base-ca',
 'PlanTL-GOB-ES/roberta-base-es-wikicat-es',
 'dccuchile/albert-base-10-spanish',
 'dccuchile/albert-base-10-spanish-distilled-mldoc',
 'dccuchile/albert-base-10-spanish-distilled-ner',
 'dccuchile/albert-base-10-spanish-distilled-pawsx',
 'dccuchile/albert-base-10-spanish-distilled-pos',
 'dccuchile/albert-base-10-spanish-distilled-qa-mlqa',
 'dccuchile/albert-base-10-spanish-distilled-qa-sqac',
 'dccuchile/albert-base-10-spanish-distilled-qa-tar',
 'dccuchile/albert-base-10-spanish-distilled-xnli',
 'dccuchile/albert-base-2-spanish',
 'dccuchile/albert-base-2-spanish-distilled-mldoc',
 'dccuchile/albert-base-2-spanish-distilled-ner',
 'dccuchile/albert-base-2-spanish-distilled-pawsx',
 'dccuchile/albert-base-2-spanish-distilled-pos',
 'dccuchile/albert-base-2-spanish-distilled-qa-mlqa',
 'dccuchile/albert-base-2-spanish-distilled-qa-sqac',
 'dccuchile/albert-base-2-spanish-distilled-qa-tar',
 'dccuchile/albert-base-2-spanish-distilled-xnli',
 'dccuchile/albert-base-4-spanish',
 'dccuchile/albert-base-4-spanish-distilled-mldoc',
 'dccuchile/albert-base-4-spanish-distilled-ner',
 'dccuchile/albert-base-4-spanish-distilled-pawsx',
 'dccuchile/albert-base-4-spanish-distilled-pos',
 'dccuchile/albert-base-4-spanish-distilled-qa-mlqa',
 'dccuchile/albert-base-4-spanish-distilled-qa-sqac',
 'dccuchile/albert-base-4-spanish-distilled-qa-tar',
 'dccuchile/albert-base-4-spanish-distilled-xnli',
 'dccuchile/albert-base-6-spanish',
 'dccuchile/albert-base-6-spanish-distilled-mldoc',
 'dccuchile/albert-base-6-spanish-distilled-ner',
 'dccuchile/albert-base-6-spanish-distilled-pawsx',
 'dccuchile/albert-base-6-spanish-distilled-pos',
 'dccuchile/albert-base-6-spanish-distilled-qa-mlqa',
 'dccuchile/albert-base-6-spanish-distilled-qa-sqac',
 'dccuchile/albert-base-6-spanish-distilled-qa-tar',
 'dccuchile/albert-base-6-spanish-distilled-xnli',
 'dccuchile/albert-base-8-spanish',
 'dccuchile/albert-base-8-spanish-distilled-mldoc',
 'dccuchile/albert-base-8-spanish-distilled-ner',
 'dccuchile/albert-base-8-spanish-distilled-pawsx',
 'dccuchile/albert-base-8-spanish-distilled-pos',
 'dccuchile/albert-base-8-spanish-distilled-qa-mlqa',
 'dccuchile/albert-base-8-spanish-distilled-qa-sqac',
 'dccuchile/albert-base-8-spanish-distilled-qa-tar',
 'dccuchile/albert-base-8-spanish-distilled-xnli',
 'dccuchile/albert-base-spanish',
 'dccuchile/albert-base-spanish-distilled-mldoc',
 'dccuchile/albert-base-spanish-distilled-ner',
 'dccuchile/albert-base-spanish-distilled-pawsx',
 'dccuchile/albert-base-spanish-distilled-pos',
 'dccuchile/albert-base-spanish-distilled-qa-mlqa',
 'dccuchile/albert-base-spanish-distilled-qa-sqac',
 'dccuchile/albert-base-spanish-distilled-qa-tar',
 'dccuchile/albert-base-spanish-distilled-xnli',
 'dccuchile/albert-large-spanish',
 'dccuchile/albert-tiny-spanish',
 'dccuchile/albert-tiny-spanish-distilled-mldoc',
 'dccuchile/albert-tiny-spanish-distilled-ner',
 'dccuchile/albert-tiny-spanish-distilled-pawsx',
 'dccuchile/albert-tiny-spanish-distilled-pos',
 'dccuchile/albert-tiny-spanish-distilled-qa-mlqa',
 'dccuchile/albert-tiny-spanish-distilled-qa-sqac',
 'dccuchile/albert-tiny-spanish-distilled-qa-tar',
 'dccuchile/albert-tiny-spanish-distilled-xnli',
 'dccuchile/albert-xlarge-spanish',
 'dccuchile/albert-xxlarge-spanish',
 'dccuchile/bert-base-spanish-wwm-cased',
 'dccuchile/bert-base-spanish-wwm-uncased',
 'dccuchile/distilbert-base-spanish-uncased',
 'dccuchile/patana-chilean-spanish-bert',
 'dccuchile/tulio-chilean-spanish-bert']

In [56]:
model_list.extend([
    "hiiamsid/sentence_similarity_spanish_es",
    "hackathon-pln-es/paraphrase-spanish-distilroberta",
    "jinaai/jina-embeddings-v2-base-es",
    "jaimevera1107/all-MiniLM-L6-v2-similarity-es",
    "jaimevera1107/roberta-similarity-es",
    "bertin-project/bertin-roberta-base-spanish",
    "jfarray/Model_dccuchile_bert-base-spanish-wwm-uncased_100_Epochs"
])

In [57]:
# exportar lista a txt
with open('es_models.txt', 'w') as f:
    for item in model_list:
        f.write("%s\n" % item)