In [1]:
import pandas as pd
import numpy as np

In [8]:
pd.read_csv("./data/sampleset_TaskA/training/english/taskA_training_en.tsv", sep='\t')

,id,jobtitle_1,jobtitle_2
0,http://data.europa.eu/esco/occupation/f2b15a0e...,soft developer,solutions developer
1,http://data.europa.eu/esco/occupation/f2b15a0e...,developer of software,software engineer
2,http://data.europa.eu/esco/occupation/d0aa0792...,software architect,software designer

In [13]:
pd.read_csv("./data/TaskA/training/english/taskA_training_en.tsv", sep='\t', names=['id1', 'id2', 'title1', 'title2'])

,id1,id2,title1,title2
0,http://data.europa.eu/esco/isco/C0110,http://data.europa.eu/esco/occupation/f2cc5978...,air commodore,flight lieutenant
1,http://data.europa.eu/esco/isco/C0110,http://data.europa.eu/esco/occupation/f2cc5978...,command and control officer,flight officer
2,http://data.europa.eu/esco/isco/C0110,http://data.europa.eu/esco/occupation/f2cc5978...,air commodore,command and control officer
3,http://data.europa.eu/esco/isco/C0110,http://data.europa.eu/esco/occupation/f2cc5978...,pilot officer,squadron leader
4,http://data.europa.eu/esco/isco/C0110,http://data.europa.eu/esco/occupation/f2cc5978...,royal airforce officer,command and control officer
...,...,...,...,...
28875,http://data.europa.eu/esco/isco/C9629,http://data.europa.eu/esco/occupation/7f346896...,groomsman,usher supervisor
28876,http://data.europa.eu/esco/isco/C9629,http://data.europa.eu/esco/occupation/7f346896...,groomsman,court usher
28877,http://data.europa.eu/esco/isco/C9629,http://data.europa.eu/esco/occupation/7f346896...,church usher,usher
28878,http://data.europa.eu/esco/isco/C9629,http://data.europa.eu/esco/occupation/7f346896...,usher supervisor,court usher
28879,http://data.europa.eu/esco/isco/C9629,http://data.europa.eu/esco/occupation/7f346896...,ticket taker,church usher

En la evaluación, tenemos tres archivos:

corpus_elements: Conjunto nuevo de trabajos sobre el cual debemos encontrar la similitud frente a uno dado

queries: solicitudes que pretenden encontrar, contrastando con todos los de corpus_elements, indicar si existe similitud (1) o no (0). Para eso habrá que definir un threshold a futuro para ver cuales colapsan a 1 y cuales a 0.

qrels: relaciones entre las queries y cada uno de los elementos del corpus. Solo se muestran los que si presentan relacion (cuarta columna, indicando con un 1).


Los datos de las queries pueden o no pertenecer al corpus conocido (la idea es que no necesariamente, y se construya pensando que no va a haber una solicitud en nuestro corpus). He encontrado algunos casos en los que si aparece en ambos. Ejemplo: lawyer

In [14]:
import sklearn

{}